### ISSUE TITLE
Itzulpen bat egiten hasi nintzen zurea aurkitu aurretik...

### ISSUE THREAD

**Issue by andergd** [Eztainu/Outer-Wilds-Euskaraz#1]
Kaixo,

Outer Wilds itzuli nahi nuen, eta Mod bat bezala gehitu. outerwildsmods.com weborritik hasi nintzen eta gaztelerazko itzulpena andaluzierara transkribatzeko beste bat egin nuen, "proba" bezala. Nire bigarren nahia euskaratzea zen, baina string batzuk baino ez itzulita neuzkanean jada norbaitek eginda zuela ikusi dut. Nire repositorioa hemen dago eskuragarri: https://github.com/andergd/OuterWildsEuskaraz

Pentsatzen ari nintzen Mod bat bezala gehitu zenezakeela itzulpena, edo zure Translation.xml fitxategia nire repositorioan partekatu, edo klonatu edo fork bat egin Mod bat bezala gehitzeko. Horrela ez dira .exe fitxategiak erabili behar ezta hizkuntzarik ordeztu.

**Comment by Eztainu** [comment]
Mod-a egin da (bi urteko atzerapenarekin baina eginda XD). 
https://github.com/Eztainu/OW_Euskaraz_Mod

**Comment by Eztainu** [comment]
Mod-a egin da (Bi urteko atzerapenarekin baina eginda XD)
https://github.com/Eztainu/OW_Euskaraz_Mod
